require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.2

Style/Documentation:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Layout/EndOfLine:
   Enabled: False

convention:Metrics/BlockLength:
  Max: 70

RSpec/MultipleExpectations:
  Max: 100

RSpec/ExampleLength:
  Max: 100
